### ISSUE TITLE
ValueError: No "site" with name gripper0_grip_site_cylinder exists.

### ISSUE THREAD

**Issue by Charlie0257** [JiangBowen0008/HACManPP#3]
@JiangBowen0008 @yilin-wu98 Thanks for your great work!

When I try to run the `OpenDoor` task in `Robosuite by` the following command
```
UDA_VISIBLE_DEVICES=0 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --algo MultiTD3 --egreedy 0.1 --location_model argmaxQ --action_mode per_point --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 2 --target_update_interval 2 --primitives suite-poke suite-pick suite-place suite-move suite-open_gripper --env suite_door --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 800 --background_clip_radius 1 --voxel_downsample_size 0.005 --reward_scale 1 --clamp_critic_max 0 --clamp_critic_min -50 --reward_aggregation average --location_model_temperature 1 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --free_move --bg_mapping_mode bbox --end_on_reached --pad_rewards --name Exp9999-0-0-robosuite_door_opening_test-ours_resume --dirname logs/hacman --seed 0 --train_steps 1000000 --ExpGroup Exp9999-robosuite_door_opening_test --ExpVariant Exp9999-robosuite_door_opening_test-ours_resume --ExpID 9999 > slurm_output/Exp9999-0-0_robosuite_door_opening_test-ours_resume.stdout
```
the error is——
```
Traceback (most recent call last):
  File "/home/charlie/anaconda3/envs/hacman/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/charlie/anaconda3/envs/hacman/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/charlie/PycharmProjects/HACManPP/third_party/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 24, in _worker
    env = env_fn_wrapper.var()
  File "/home/charlie/PycharmProjects/HACManPP/third_party/stable-baselines3/stable_baselines3/common/env_util.py", line 82, in _init
    env = env_id(**env_kwargs)
  File "/home/charlie/PycharmProjects/HACManPP/hacman_suite/envs/door.py", line 42, in __init__
    Door.__init__(self,
  File "/home/charlie/PycharmProjects/HACManPP/third_party/robosuite/robosuite/environments/manipulation/door.py", line 176, in __init__
    super().__init__(
  File "/home/charlie/PycharmProjects/HACManPP/third_party/robosuite/robosuite/environments/manipulation/manipulation_env.py", line 160, in __init__
    super().__init__(
  File "/home/charlie/PycharmProjects/HACManPP/third_party/robosuite/robosuite/environments/robot_env.py", line 211, in __init__
    super().__init__(
  File "/home/charlie/PycharmProjects/HACManPP/third_party/robosuite/robosuite/environments/base.py", line 147, in __init__
    self._reset_internal()
  File "/home/charlie/PycharmProjects/HACManPP/third_party/robosuite/robosuite/environments/manipulation/door.py", line 389, in _reset_internal
    super()._reset_internal()
  File "/home/charlie/PycharmProjects/HACManPP/third_party/robosuite/robosuite/environments/robot_env.py", line 498, in _reset_internal
    super()._reset_internal()
  File "/home/charlie/PycharmProjects/HACManPP/third_party/robosuite/robosuite/environments/base.py", line 287, in _reset_internal
    self._setup_references()
  File "/home/charlie/PycharmProjects/HACManPP/third_party/robosuite/robosuite/environments/manipulation/door.py", line 314, in _setup_references
    super()._setup_references()
  File "/home/charlie/PycharmProjects/HACManPP/third_party/robosuite/robosuite/environments/robot_env.py", line 313, in _setup_references
    robot.setup_references()
  File "/home/charlie/PycharmProjects/HACManPP/third_party/robosuite/robosuite/robots/single_arm.py", line 220, in setup_references
    self.eef_cylinder_id = self.sim.model.site_name2id(self.gripper.important_sites["grip_cylinder"])
  File "wrappers.pxi", line 1051, in mujoco_py.cymj.PyMjModel.site_name2id
ValueError: No "site" with name gripper0_grip_site_cylinder exists. Available "site" names = ('xaxis', 'yaxis', 'zaxis', 'table_top', 'gripper0_ft_frame', 'gripper0_grip_site', 'gripper0_ee_x', 'gripper0_ee_y', 'gripper0_ee_z', 'Door_default_site', 'Door_handle').

```

Could you give me some advice to solve this issue? My `mujoco-py` version is `2.1.2.14`. And when I run` ManiSkill2` and `DoubleBin Env` related tasks, no errors are outputted :)

Best,
Charlie

**Comment by yilin-wu98** [comment]
go to third_party/robosuite/robosuite/models/assets/grippers/panda_gripper.xml. uncomment line 26: ```<!--                <site name="grip_site_cylinder" pos="0 0 0" size="0.005 10" rgba="0 1 0 0.3" type="cylinder" group="1"/>-->``` to ```<site name="grip_site_cylinder" pos="0 0 0" size="0.005 10" rgba="0 1 0 0.3" type="cylinder" group="1"/>```. We will update the submodule soon.

**Comment by Charlie0257** [comment]
@yilin-wu98 Thanks for your reply! It works now :)
